{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aigent-cluster.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
