---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aigent-ds.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "aigent-ds.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "aigent-ds.selectorLabels" . | nindent 8 }}
    spec:
{{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Release.Name }}-sa
{{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
{{- if .Values.resources }}
{{- if .Values.resources.enabled }}
        resources:
          requests:
            cpu: "{{ .Values.resources.cpu.request }}"
            memory: "{{ .Values.resources.memory.request }}"
          limits:
            cpu: "{{ .Values.resources.cpu.limit }}"
            memory: "{{ .Values.resources.memory.limit }}"
{{- end }}
{{- end }}
{{- if .Values.daemonset.args }}
        args:
          {{- range .Values.daemonset.args }}
          - {{ . | quote }}
          {{- end }}
{{- end }}
        env:
          - name: AGENT_TYPE
            value: "aigent"
          - name: AGENT_BASE_ID
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-agentid
                key: instance_uid
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
{{- if .Values.daemonset.controlplane }}
          - name: CONTROLPLANE_ENDPOINT
            value: "{{ .Values.daemonset.controlplane.endpoint }}"
          - name: ADMISSION_TOKEN
            value: "{{ .Values.daemonset.controlplane.admission_token }}"
{{- end }}
{{- if .Values.daemonset.butler_endpoint }}
          - name: BUTLER_ENDPOINT
            value: "{{ .Values.daemonset.butler_endpoint }}"
{{- end }}
{{- if .Values.daemonset.cluster_name }}
          - name: CLUSTER_NAME
            value: "{{ .Values.daemonset.cluster_name }}"
{{- end }}
{{- if .Values.daemonset.deployment_env }}
          - name: DEPLOYMENT_ENV
            value: "{{ .Values.daemonset.deployment_env }}"
{{- end }}
        {{- range $name, $value := .Values.daemonset.env }}
          - name: {{ $name }}
            value: "{{ $value }}"
        {{- end }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: dockerlogs
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: containerdlogs
          mountPath: /var/log/pods
          readOnly: true
        ports:
          - name: otelhttp
            containerPort: {{ .Values.service.otelhttp.port }}
          - name: otelgrpc
            containerPort: {{ .Values.service.otelgrpc.port }}
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 2Gi
      - name: varlog
        hostPath:
          path: /var/log
      - name: dockerlogs
        hostPath:
          path: /var/lib/docker/containers
      - name: containerdlogs
        hostPath:
          path: /var/log/pods
{{- if .Values.daemonset.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.daemonset.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.daemonset.tolerations }}
      tolerations:
        {{- toYaml .Values.daemonset.tolerations | nindent 8 }}
{{- end }}
